import { Tabs, useRouter, type Href } from "expo-router";
import { View, StyleSheet } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { colors, palette } from "@/theme";

/**
 * 5-slot tab bar (plan §7). Phase 1 ships Home + Profile as functional and
 * Insights/Academics as placeholders; the center (+) quick actions land in
 * Phase 3.
 *
 * The tab bar adds the bottom safe-area inset to its height/padding so the icons
 * clear the Android gesture / 3-button nav bar (edge-to-edge is on by default in
 * SDK 55).
 */
export default function TabsLayout() {
  const insets = useSafeAreaInsets();
  const router = useRouter();

  return (
    <Tabs
      screenOptions={{
        headerStyle: { backgroundColor: colors.navy },
        headerTintColor: colors.textInverse,
        headerTitleStyle: { fontWeight: "700" },
        tabBarActiveTintColor: colors.navy,
        tabBarInactiveTintColor: "#9aa3bd",
        tabBarLabelStyle: { fontSize: 10, fontWeight: "600" },
        tabBarStyle: {
          height: 58 + insets.bottom,
          paddingTop: 8,
          paddingBottom: insets.bottom + 8,
          borderTopColor: colors.border,
          backgroundColor: "#ffffff",
        },
      }}
    >
      <Tabs.Screen
        name="index"
        options={{
          title: "Home",
          headerShown: false,
          tabBarIcon: ({ color, size, focused }) => (
            <Ionicons name={focused ? "home" : "home-outline"} color={color} size={size} />
          ),
        }}
      />
      <Tabs.Screen
        name="learning"
        options={{
          title: "Learning",
          headerShown: false,
          tabBarIcon: ({ color, size, focused }) => (
            <Ionicons name={focused ? "book" : "book-outline"} color={color} size={size} />
          ),
        }}
        listeners={{
          // Always land on the Learning hub when the tab is tapped (same
          // rationale as the Academics/Health tabs — a deep-link into a
          // learning screen shouldn't strand the user without a route back).
          tabPress: (e) => {
            e.preventDefault();
            // Cast: expo-router's typed routes are regenerated by the dev server;
            // the freshly-added /(tabs)/learning isn't in the stale union yet.
            router.navigate("/(tabs)/learning" as Href);
          },
        }}
      />
      {/* Center (+) — intercepts the tab press to open the quick-actions
          modal instead of navigating to a screen (plan §7 / Phase 3). */}
      <Tabs.Screen
        name="create"
        options={{
          title: "",
          tabBarIcon: () => (
            <View style={styles.plus}>
              <Ionicons name="add" color={colors.textInverse} size={26} />
            </View>
          ),
        }}
        listeners={{
          tabPress: (e) => {
            e.preventDefault();
            router.push("/quick-actions");
          },
        }}
      />
      <Tabs.Screen
        name="academics"
        options={{
          title: "Academics",
          headerShown: false,
          tabBarIcon: ({ color, size, focused }) => (
            <Ionicons name={focused ? "school" : "school-outline"} color={color} size={size} />
          ),
        }}
        listeners={{
          // Always land on the Academics hub when the tab is tapped. Without
          // this, a sub-screen reached via a Home "Explore" deep-link
          // (router.push to /(tabs)/academics/attendance) can leave the user
          // stranded with no back route to the hub — the nested stack's
          // initialRouteName anchor isn't guaranteed across a cross-tab push.
          tabPress: (e) => {
            e.preventDefault();
            router.navigate("/(tabs)/academics");
          },
        }}
      />
      <Tabs.Screen
        name="health"
        options={{
          title: "Health",
          headerShown: false,
          tabBarIcon: ({ color, size, focused }) => (
            <Ionicons name={focused ? "heart" : "heart-outline"} color={color} size={size} />
          ),
        }}
        listeners={{
          // Always land on the Health hub when the tab is tapped, so a sub-screen
          // reached via a Home/Explore deep-link never strands the user without a
          // route back to the hub (same rationale as the Academics tab).
          tabPress: (e) => {
            e.preventDefault();
            router.navigate("/(tabs)/health");
          },
        }}
      />
    </Tabs>
  );
}

const styles = StyleSheet.create({
  plus: {
    width: 46,
    height: 46,
    borderRadius: 23,
    marginTop: -14,
    backgroundColor: palette.primary600,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: palette.primary800,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
});
